# Generated by Django 5.1 on 2025-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkeys',
            name='format',
            field=models.CharField(choices=[('jwk', 'jwk')], default='jwk', max_length=100, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='organizationkeys',
            name='type',
            field=models.CharField(choices=[('secp256k1', 'secp256k1'), ('secp256r1', 'secp256r1')], default='secp256k1', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='organizationkeys',
            name='value',
            field=models.JSONField(default=dict, help_text='Add here you Private Key or your information', max_length=2000, verbose_name='Value'),
        ),
    ]
