# Generated by Django 5.1 on 2025-04-20 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationkeys_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkeys',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='organizationkeys',
            name='type',
            field=models.CharField(choices=[('secp256k1', 'secp256k1'), ('secp256r1', 'secp256r1')], default='secp256k1', max_length=20, primary_key=True, serialize=False, verbose_name='Type'),
        ),
    ]
