# Generated by Django 5.1 on 2025-03-25 15:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedVerifiableCredential',
            fields=[
                ('vc_id', models.CharField(max_length=4000, primary_key=True, serialize=False, verbose_name='VC Identifier')),
                ('vc_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4000), size=None, verbose_name='VC Types')),
                ('hash', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Credential hash')),
                ('issuance_date', models.DateTimeField(verbose_name='Issuance Date')),
                ('status', models.BooleanField(default=False, verbose_name='Revocation status')),
                ('revocation_type', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Revocation Type')),
                ('revocation_info', models.JSONField(blank=True, null=True, verbose_name='Revocation Information')),
                ('holder', models.CharField(max_length=4000, verbose_name='Holder DID')),
            ],
        ),
        migrations.CreateModel(
            name='StatusList2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('current_index', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(131071)])),
            ],
            options={
                'verbose_name': 'StatusList2021',
                'verbose_name_plural': 'StatusLists2021',
            },
        ),
        migrations.CreateModel(
            name='VerifiableCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Credential (JWT Format)')),
            ],
            options={
                'verbose_name': 'Verifiable Credential',
                'verbose_name_plural': 'Verifiable Credentials',
            },
        ),
    ]
