# Generated by Django 5.1 on 2025-03-25 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbsiAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VerifiableAuthorisationToOnboard', 'VerifiableAuthorisationToOnboard'), ('VerifiableAccreditationToAttest', 'VerifiableAccreditationToAttest'), ('VerifiableAccreditationToAccredit', 'VerifiableAccreditationToAccredit'), ('VerifiableAccreditationForTrustChain', 'VerifiableAuthorisationForTrustChain')], max_length=100, verbose_name='Accreditation Type')),
                ('token', models.CharField(choices=[('vp_token', 'vp_token'), ('id_token', 'id_token')], default='id_token', max_length=100, verbose_name='Response Type')),
            ],
        ),
        migrations.CreateModel(
            name='EbsiAccreditationWhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2000, verbose_name='type')),
                ('did', models.CharField(max_length=2000, verbose_name='DID')),
            ],
        ),
        migrations.CreateModel(
            name='EbsiTermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='VC Type')),
                ('vc_schema', models.CharField(max_length=1000, null=True)),
                ('attribute_id', models.CharField(max_length=4000, null=True, verbose_name='Attribute ID')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialAccreditationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2000, verbose_name='type')),
                ('accredited_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='Accredit for type')),
                ('accredited_schema', models.CharField(max_length=4000, null=True, verbose_name='Accredited Schema')),
                ('attribute_id', models.CharField(max_length=4000, null=True, verbose_name='Attribute ID')),
            ],
            options={
                'verbose_name': 'Potential Accreditation information',
                'verbose_name_plural': 'Potential Accreditations information',
            },
        ),
        migrations.CreateModel(
            name='ProxyAPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_id', models.CharField(max_length=64, verbose_name='proxy_id')),
            ],
        ),
    ]
