# Generated by Django 5.1 on 2025-03-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('ebsi', '0001_initial'),
        ('openid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebsiaccreditation',
            name='presentation_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openid.presentationdefinition'),
        ),
        migrations.CreateModel(
            name='AccreditationToAccredit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ebsi.ebsiaccreditationwhitelist',),
        ),
        migrations.CreateModel(
            name='AccreditationToAttest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ebsi.ebsiaccreditationwhitelist',),
        ),
        migrations.CreateModel(
            name='AccreditationToOnboard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ebsi.ebsiaccreditationwhitelist',),
        ),
        migrations.AddField(
            model_name='ebsitermsofuse',
            name='vc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.verifiablecredential'),
        ),
        migrations.AddField(
            model_name='ebsiaccreditationwhitelist',
            name='schema',
            field=models.ManyToManyField(related_name='white_lists', to='ebsi.potentialaccreditationinformation'),
        ),
        migrations.AlterUniqueTogether(
            name='ebsiaccreditationwhitelist',
            unique_together={('type', 'did')},
        ),
    ]
