# Generated by Django 4.1.3 on 2024-09-19 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import openid.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceInformation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('credential_issuer_metadata', models.JSONField(blank=True, default=dict, max_length=22500, verbose_name='Credential Issuer Metadata')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Issuance Information',
                'verbose_name_plural': 'Issuance Information',
            },
        ),
        migrations.CreateModel(
            name='NonceManager',
            fields=[
                ('nonce', models.CharField(max_length=2000, primary_key=True, serialize=False, verbose_name='Nonce')),
                ('state', models.JSONField(blank=True, null=True, verbose_name='State')),
                ('did', models.CharField(max_length=2000, verbose_name='Did')),
            ],
            options={
                'verbose_name': 'Nonce Manager',
                'verbose_name_plural': 'Nonces Manager',
            },
        ),
        migrations.CreateModel(
            name='PresentationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_id', models.CharField(blank=True, max_length=2500, unique=True, verbose_name='Identifier')),
                ('format', models.JSONField(blank=True, verbose_name='Format')),
                ('descriptors', models.JSONField(verbose_name='Input Descriptors')),
            ],
            options={
                'verbose_name': 'Presentation Definition',
                'verbose_name_plural': 'Presentation Definitions',
            },
        ),
        migrations.CreateModel(
            name='VerifyFlow',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=2000, verbose_name='Scope')),
                ('response_type', models.CharField(choices=[('vp_token', 'vp_token'), ('id_token', 'id_token')], default='vp_token', max_length=100, verbose_name='Response Type')),
                ('presentation_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openid.presentationdefinition')),
            ],
            options={
                'verbose_name': 'Verify Flow',
                'verbose_name_plural': 'Verify Flows',
            },
        ),
        migrations.CreateModel(
            name='IssuanceFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='openid', max_length=2000, verbose_name='Scope')),
                ('response_type', models.CharField(choices=[('vp_token', 'vp_token'), ('id_token', 'id_token')], default='id_token', max_length=100, verbose_name='Response Type')),
                ('is_deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('credential_types', models.CharField(max_length=2000, verbose_name='Credential Type')),
                ('credential_schema_address', models.CharField(max_length=2000, verbose_name='Credential Schema')),
                ('revocation', models.CharField(blank=True, choices=[('status_list_2021', 'StatusList2021')], default=openid.enums.RevocationTypes['status_list_2021'], max_length=100, null=True, verbose_name='Type of revocation on EBSI')),
                ('expires_in', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expires in (s)')),
                ('presentation_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openid.presentationdefinition')),
            ],
            options={
                'verbose_name': 'Issuance Flow',
                'verbose_name_plural': 'Issuance Flows',
            },
        ),
    ]
