# Generated by Django 4.1.3 on 2024-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationdefinition',
            name='format',
            field=models.JSONField(verbose_name='Format'),
        ),
    ]
