name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Installing danger, code-coverage and jira-danger
        run: |
          npm init --yes
          npm install danger danger-plugin-istanbul-coverage danger-plugin-jira-issue --dev

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install deps
        run:
          pip install -r requirements.txt
          pip install multiformats

      # - name: Run pylint
      #   run: pylint project/ --rcfile=.pylintrc >> pylint.json
      #   continue-on-error: true

      - name: Danger
        run: npx danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
